import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// TODO
// 4. add test routing
// 4.1 param routing
// 4.2 add pagination
// 4.3 add list of products with link to the separate product
// 5. add mock server
// 6. add few pages with api integration with loader (all data is not preloaded)
// 7. add few pages with api integration with loader (some data is preloaded)
// 8. add auth and not auth pages
// 9. error handling
// 10. caching?
// * try page vs app router
// * deploying


// done

// 0. project structure - online sales
// 1. cleanup layout
// 2. add ui-kit and add start layout example
// 3. add custom themes + theme toggler
