import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from '../components/layout/header';
import { MainContent } from '../components/layout/mainContent';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex flex-col flex-1 items-center justify-center font-sans">
          <Header />
          <MainContent>
            {children}
          </MainContent>
        </div>
      </body>
    </html>
  );
}

// TODO
// 4.4 add search with options
// 5. add mock server
// 6. add few pages with api integration with loader (all data is not preloaded)
// 7. add few pages with api integration with loader (some data is preloaded)
// 7.1 add orders pagination
// 7.2 add image to products + image handling
// 7.3 grid?
// 8. add auth and not auth pages
// 9. error handling
// 10. caching?
// 11. add inner login page without upper layout
// 12. highlight basket-orders-itc when subpage opened
// * try page vs app router
// * deploying


// done

// 0. project structure - online sales
// 1. cleanup layout
// 2. add ui-kit and add start layout example
// 3. add custom themes + theme toggler
// 4. add test routing
// 4.1 param routing
// 4.2 add list of products with link to the separate product
// 4.3 add redirect to pages
